# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: master
    hooks:
      #
      # Go Build
      #
      - id: go-build-mod
      #
      # Go Mod Tidy
      #
      - id: go-mod-tidy
      #
      # Go Test
      #
      - id: go-test-mod
      #
      # Go Vet
      #
      - id: go-vet-mod
      #
      # Revive
      #
      - id: go-revive-mod
      #
      # GoSec
      #
      - id: go-sec-mod
      #
      # StaticCheck
      #
      - id: go-staticcheck-mod
      #
      # StructSlop
      #
      - id: go-structslop-mod
      #
      # Formatters
      #
      - id: go-imports      # replaces go-fmt
      #
      # Style Checkers
      #
      - id: go-lint
      - id: go-critic
