name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    name: build-verify-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache-dependency-path: ./go.mod
      - uses: pre-commit-ci/lite-action@v1.0.1

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          only-new-issues: true

  tag:
    runs-on: ubuntu-latest
    needs: [pre-commit, golangci]
    if: ${{ github.ref == 'refs/heads/main' && needs.pre-commit.result == 'success' && needs.golangci.result == 'success' }}
    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
